#!/usr/bin/env bash

show_commands () {
    cat << EOF
$ICON Comandos disponíveis:

sh dev start-dev             - Inicia os containers em modo Dev (Watch)
sh dev npm                   - Instala pacotes utilizando o NPM

EOF
}

start_dev () {
   docker-compose up -d
}

execute_npm () {
    docker-compose run --rm app npm $@
}

if [ $# -gt 0 ]; then

    case "$1" in

    "start-dev") start_dev ;;
    "npm") execute_npm $@ ;;

    *) show_commands;;

    esac

else
    show_commands
fi
